- platform: mqtt
  name: "Temperature"
  state_topic: "buro/dht22"
  unit_of_measurement: '°C'
  value_template: "{{ value_json.temperature }}"
- platform: mqtt
  name: "Humidity"
  state_topic: "buro/dht22"
  unit_of_measurement: '%'
  value_template: "{{ value_json.humidity }}"